### ISSUE TITLE
A typo is found in "Papers"

### ISSUE THREAD

**Issue by luyanaa** [georgezouq/awesome-ai-in-finance#18]
[FinRL: A Deep Reinforcement Learning Library for Automated Stock Trading in Quantitative Finance, 2011](https://arxiv.org/abs/2011.09607) - Introduce a DRL library FinRL that facilitates beginners to expose themselves to quantitative finance and to develop their own stock trading strategies.

The "2011" should be 2020.

**Comment by georgezouq** [comment]
Fix in this [commit](https://github.com/georgezouq/awesome-ai-in-finance/commit/e489acc99fa8e6a54d67af480b441b4a68baff3d)
